name: Release (MacOS, Linux)

on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    name: Deploy for ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux-18, linux-20, linux-22]

        include:
          - name: linux-18
            os: ubuntu-18.04
            artifact_name: matchstick
            asset_name: binary-linux-18
          - name: linux-20
            os: ubuntu-20.04
            artifact_name: matchstick
            asset_name: binary-linux-20
          - name: linux-22
            os: ubuntu-22.04
            artifact_name: matchstick
            asset_name: binary-linux-22

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.68.0
      - run: sudo apt-get install protobuf-compiler

      - name: Build
        run: cargo build --release && mv target/release/${{ matrix.artifact_name }} target/release/${{ matrix.asset_name }}

      - name: Upload binaries to release
        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token && gh release upload ${GITHUB_REF##*/} target/release/${{ matrix.asset_name }}
