name: Release (MacOS, Linux)

on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    name: Deploy for ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [macos-10.15, macos-11]

        include:
          - name: macos-10.15
            os: macos-10.15
            artifact_name: matchstick
            asset_name: binary-macos-10.15
          - name: macos-11
            os: macos-11
            artifact_name: matchstick
            asset_name: binary-macos-11

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.68.0
      - run: brew install protobuf

      - name: Build
        run: cargo build --release && mv target/release/${{ matrix.artifact_name }} target/release/${{ matrix.asset_name }}

      - name: Upload binaries to release
        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token && gh release upload ${GITHUB_REF##*/} target/release/${{ matrix.asset_name }}
